plugins {
    id 'application'
    id 'idea'
}

dependencies {
    implementation project(':net-basic')

    annotationProcessor project(':net-basic-compiler')
}

def generatedSourcesDir = file('build/generated/sources/annotationProcessor/java/main')

sourceSets {
    main {
        java {
            srcDir generatedSourcesDir
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.getGeneratedSourceOutputDirectory().set(generatedSourcesDir)
}

idea {
    module {
        generatedSourceDirs += file('build/generated/sources/annotationProcessor/java/main')
    }
}

application {
    mainClass = 'com.example.chat.Main'
}